import Head from 'next/head'
import Link from 'next/link'
/*import styles from '../styles/Home.module.css'*/

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>TreinaCook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./public/favicon.ico" />
        <link rel="stylesheet" href="./styles/styles.css" />
        
      </Head>

      <header className="header">

        <div>
          <Link href="/">
          <a>
         <p>TreinaCook</p>
         </a>
         </Link>
      </div>
      </header>
      <main className='main'>
        <figure className="recipe-card">
          <Link href="/receitas/frango/frango-desfiado">
            <a>
              <img className = "imagem" src="https://img.itdg.com.br/tdg/images/blog/uploads/2021/11/shutterstock_681361963-768x512.jpg" />
            </a>
          </Link>
        
          
          <div className="descricao">Como desfiar frango no microondas</div>
          <figcaption className="categoria">Frango</figcaption>
        </figure>
      </main>

      <footer className='footer'>
        <p> &copy;TreinaCook</p>
      </footer>
    </div>
  )
}
